services:
  web:
    build: docker/php-apache
    container_name: php8.2-apache
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html

  database:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80

volumes:
  mysql_data: